name = "pudong-invest-platform"
main = "src/index.ts"
compatibility_date = "2025-01-09"
workers_dev = true
pages_build_output_dir = "../dist"

[vars]
PROPERTY_SHEET = "T7TAbrrdXazsozsyELrcMUMAnnf"
PROPERTY_BUILDING_SHEET_ID = "tblbuildingid"
POLICY_SHEET = "T7TAbrrdXazsozsyELrcMUMAnnf"
POLICY_SHEET_ID = "tblpolicyid"
STATS_SHEET_ID = "tblstatsid"
NEWS_SHEET = "T7TAbrrdXazsozsyELrcMUMAnnf"
NEWS_SHEET_ID = "tblnewsid"
CLUE_SHEET = "T7TAbrrdXazsozsyELrcMUMAnnf"
CLUE_SHEET_ID = "tbli8WVDDVo2dF90"
CUSTOMER_SHEET = "T7TAbrrdXazsozsyELrcMUMAnnf"
CUSTOMER_SHEET_ID = "tblRdTK6zegBRhDW"
VISIT_SHEET = "T7TAbrrdXazsozsyELrcMUMAnnf"
VISIT_SHEET_ID = "tbl6HIz5vDvnv5w8"
PROPERTY_PARK_SHEET_ID = "4hdJSg"
PROPERTY_UNIT_SHEET_ID = "4hdJSi"
PROPERTY_INDUSTRY_SHEET_ID = "4hdJSj"
SUPABASE_URL = "https://rgnncmgrumwjjgzyhmkt.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnbm5jbWdydW13ampnenlobWt0Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NzczMTAwNSwiZXhwIjoyMDkzMzA3MDA1fQ.Rrq95ziEwcTmX1NNz62ZqGsN8GvyZcutqzAIwC7PkC8"
NVIDIA_API_KEY = "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"
